version: '3.7'

networks:
  nginx_net_bridge:
    external: true

services:
  tiktok_signature:
    image: registry.cn-hangzhou.aliyuncs.com/monve/tiktok_signature:1.0.1
    container_name: tiktok_signature
    restart: always
    ports:
      - "3280:80"
    networks:
      - nginx_net_bridge
    logging:
      options:
        max-size: "100M"
