version: '3.7'

networks:
  net_bridge:
    driver: bridge

services:
  tiktok_signature:
    image: registry.cn-hangzhou.aliyuncs.com/monve/tiktok_signature:1.0.3
    container_name: tiktok_signature
    restart: always
    ports:
      - "3202:3202"
    networks:
      - net_bridge
    logging:
      options:
        max-size: "100M"
